apiVersion: apps/v1
kind: Deployment

metadata:
  name: lab-1-deployment

spec:
  selector:
    matchLabels:
      app: lab-1-pods
  template:
    metadata:
      labels:
        app: lab-1-pods
    spec:
      containers:
        - name: tiddi
          image: ghcr.io/kunalsin9h/tiddi-container:latest
