apiVersion: v1
kind: Service

metadata:
  name: numbers-web

spec:
  selector:
    app: numbers-web
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer # This can listen on localhost:8080 and send to numbers-web:80
  # type: LoadBalancer is for accepting request from networks outside the cluster

