apiVersion: v1
kind: PersistentVolume

metadata:
  name: pv01

spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: /volumes/pv01 
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: node-label-key
            operator: In
            values:
              - node-label-value
