# App Manifest always specify the version of Kubernetes API
apiVersion: v1

# And the type of resource
kind: Pod

metadata: 
  name: hello-kiamol-69

spec:
  containers:
    - name: web
      image: kiamol/ch02-hello-kiamol
      env:
        - name: FIRST
          value: "first_value"
        - name: SECOND
          value: "second_value"
        - name: FROM_CONFIG_MAP
          valueFrom:
            configMapKeyRef:
              name: some_name_of_configmap
              key: some_key_in_that_configmap
      envFrom:
        - configMapRef:
            name: name_of_config_map # load the entire config map data 

