apiVersion: apps/v1
kind: Deployment

metadata:
  name: sleep

spec:
  selector:
    matchLabels:
      app: sleep

  template:
    metadata:
      labels:
        app: sleep    
    spec:
      containers:
        - name: sleep  
          image: kiamol/ch03-sleep
          volumeMounts:
            - name: data 
              mountPath: /data
      volumes: # are at pod level, i.e parallel to containers 
        - name: data
          emptyDir: {} # type is empty directory

